### ISSUE TITLE
In-snippet imports for outside packages don't work

### ISSUE THREAD

**Issue by neil-morrison44** [bbc/typescript-docs-verifier#11]
We've got our types stored in an outside package, which we want to refer to while doing examples e.g.

```typescript
import { something } from "our-currentPackage"
import { TypeOfSomethingElse } from "our-types"
```
Currently the first line works, and any imports inside the `"our-currentPackage"` can refer to outside packages, but the second one doesn't.

It seems like the issue is caused by the compiled scripts being placed in a tmp dir in:
https://github.com/bbc/typescript-docs-verifier/blob/master/index.ts#L18
```typescript
const compiledDocsFolder = path.join(os.tmpdir(), 'compiled-docs')
```

`os.tmpdir` does keep things neater so I assume you'll want to keep it as the default - but could we add a CLI option to switch this for `process.cwd()`? 
(which'll mean the compiled scripts can access the same packages, but could have other effects I've not considered)

Thanks

**Comment by paulbrimicombe** [comment]
@neil-morrison44 I'll try to get to this by the end of the week. Can you pin to an earlier version temporarily as a workaround (see https://github.com/bbc/typescript-docs-verifier/blob/master/CHANGELOG#L12)?

**Comment by neil-morrison44** [comment]
No worries, we're already using a fork ( so we can get the fix in for https://github.com/bbc/typescript-docs-verifier/pull/10 ) & I've made the change there

**Comment by paulbrimicombe** [comment]
Hi @neil-morrison44 I've just made some changes and pushed version `2.2.0-alpha1` — this _should_ fix both of you problems. Can you test it and let me know? If it's all working correctly for you then I'll publish it as a stable release.

What I've changed is:

- The project's `node_modules` is symlinked to the directory where the snippets are compiled so you can use project dependencies in your snippets
- Scoped packages are now supported
- You can now reference files / folders inside packages as well

Thanks for your PR for the latter issue — I went with a slightly different implementation in the end but your PR definitely helped a lot!

**Comment by neil-morrison44** [comment]
@paulbrimicombe Just gave it a run there, think there's an issue where it's including the main file's name in the import for "other" files


If I've got a main file named
```
"main": "./dist/index-test.js",
```
and my import is
```ts
import { something } from "@our/package/feature/thing"
```
then it'll output
```ts
import { something } from "dist/index-test/feature/thing"
```
instead of
```ts
import { something } from "dist/feature/thing"
```

**Comment by paulbrimicombe** [comment]
Ah. I thought that the packages were relative to `main` (e.g. if `main` is a directory as in the tests) but it seems from running some tests that they're relative to the package root. I'll push a fix for that @neil-morrison44 . Thanks for testing so quickly.

**Comment by paulbrimicombe** [comment]
@neil-morrison44 I've just merged (but not released) what I think is an appropriate fix for this. Looking back at your comment though, I'm not quite sure the imports you've listed are correct:

> If I've got a main file named
> 
> ```
> "main": "./dist/index-test.js",
> ```
> 
> and my import is
> 
> ```ts
> import { something } from "@our/package/feature/thing"
> ```
> 
> [it should be transformed to]
> 
> ```ts
> import { something } from "dist/feature/thing"
> ```

I just did some local testing and I _think_ node resolves files inside the package relative to the root of the package, so to get `dist/feature/thing` you'd have to import `"@our/package/dist/feature/thing"`. Can you confirm that's what you'd expect please before I do another release?

For example, if I were trying to import the `SnippetCompiler` from this source code I'd have to do:

```ts
import { SnippetCompiler } from 'typescript-docs-verifier/dist/src/SnippetCompiler'
```

The `package.json` has a `main` of `dist/index.js`. The same seems to be true even if the `main` is set to just `dist`.

**Comment by neil-morrison44** [comment]
@paulbrimicombe oops - yeah, the 'dist' directory would need to be in there

**Comment by paulbrimicombe** [comment]
> @paulbrimicombe oops - yeah, the 'dist' directory would need to be in there

@neil-morrison44 can you try `2.2.0-alpha2` please and check it does what you expect it to?

**Comment by neil-morrison44** [comment]
@paulbrimicombe 👍🏻  `2.2.0-alpha2` seems to work fine
