### ISSUE TITLE
Support `exports` package entrypoint

### ISSUE THREAD

**Issue by wemeetagain** [bbc/typescript-docs-verifier#17]
typescript-docs-verifier currently requires the package to define a `main` entry in its package.json.

It should also allow for an `exports` to be defined instead.

See https://nodejs.org/api/packages.html#packages_package_entry_points

**Comment by paulbrimicombe** [comment]
This has been on my radar for a bit @wemeetagain — I'll see if I can get to it in the next couple of weeks. It may be that the library only supports `exports.require` and `main` and ignores `exports.import` to start with.

**Comment by wemeetagain** [comment]
Thanks @paulbrimicombe for the thorough explanation.

Unfortunately, we'll have to wait for sub-path exports and `import` conditional export support lands in order to test.
We've been migrating our typescript codebase to use ESM and now make fairly extensive use of sub-path exports and use the `import` conditional export only.

**Comment by paulbrimicombe** [comment]
Ah OK. I'll try to take a look at that soon. Can you give me an example repo or is all of this closed-source @wemeetagain ?

**Comment by wemeetagain** [comment]
I'd also like to apply this project to https://github.com/libp2p/js-libp2p, another example of an ESM project that makes use of sub path exports and `import` conditional export.
See https://github.com/libp2p/js-libp2p/issues/1228

**Comment by dapplion** [comment]
Friendly ping, would love to keep using the tool. Let us know if you need help testing

**Comment by paulbrimicombe** [comment]
@dapplion @wemeetagain Apologies again that this has taken so long for me to get round to but I've just released version `2.3.0` which has support for `exports` — it should cope with explicit and wildcard subpaths.

@wemeetagain I've tested it against `lodestar` and it runs fine but reports what I think is a genuine problem in one of the code blocks.

Please let me know if you have any problems at all!

**Comment by wemeetagain** [comment]
Woohoo! thanks :) We'll test it out and let you know

**Comment by wemeetagain** [comment]
Works great! Re-enabled in our project now
https://github.com/ChainSafe/lodestar/pull/4507

**Comment by paulbrimicombe** [comment]
Thanks @wemeetagain . Please get in touch if you have any other problems / requests in the future!
