### ISSUE TITLE
Inconsistent Results on Windows

### ISSUE THREAD

**Issue by maschad** [bbc/typescript-docs-verifier#26]
Running this on a Windows OS will result in the compiling not finding any Typescript snippets. I suspect this may be because the _Snippet Compiler_ uses [`path.basename`](https://github.com/bbc/typescript-docs-verifier/blob/0b093c74dc5ed06fd92c4d46f01493cb8d8c4618/src/SnippetCompiler.ts#L133) which will lead to inconsistent results on a [Windows vs Posix](https://nodejs.org/api/path.html#windows-vs-posix). If the intention is to work with POSIX file paths on any operating system, it may be best to use [path.posix](https://nodejs.org/api/path.html#pathposix)

**Comment by paulbrimicombe** [comment]
Ah. Thanks very much for this @maschad this is good to know! I'll see if I can get a fix in for this soon.

**Comment by paulbrimicombe** [comment]
Sorry I've taken so long to get to this. There were a number of problems (`path.basename` not being one of them). I've published version 2.4.1 which should now work on Windows. Let me know if there are any other problems!

**Comment by maschad** [comment]
Awesome! I'll upgrade and give it a try! Thanks.
