### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by kyleknighted** [bbc/typescript-docs-verifier#3]
Hello maintainers,

When I try to run `node_modules/.bin/typescript-docs-verifier --input-files src/components/Alert.md` I get the following error

```
$ node_modules/.bin/typescript-docs-verifier --input-files src/components/Alert.md
ℹ Compiling documentation TypeScript code snippets from src/components/Alert.md
⠙ TypeError: Cannot read property 'replace' of undefined
at new LocalImportSubstituter (/Users/me/Code/master/project-repos/server/web-interface/node_modules/typescript-docs-verifier/src/LocalImportSubstituter.ts:10:47)
at SnippetCompiler.extractAllCodeBlocks (/Users/me/Code/master/project-repos/server/web-interface/node_modules/typescript-docs-verifier/src/SnippetCompiler.ts:60:31)
at async SnippetCompiler.compileSnippets (/Users/me/Code/master/project-repos/server/web-interface/node_modules/typescript-docs-verifier/src/SnippetCompiler.ts:45:24)
at async doCompilation (/Users/me/Code/master/project-repos/server/web-interface/node_modules/typescript-docs-verifier/bin/compile-typescript-docs.ts:58:19)
✖ 
error Command failed with exit code 1.
```

The markdown file consists of

```
# Alert

```tsx
<Alert>
  <i className="fa fa-exclamation-triangle fa-fw fa-lg" />
  <strong>Default</strong> Lorem ipsum dolor sit amet consectetur adipisicing elit.
</Alert>```
```

I have tried `ts`, `tsx`, `typescript`, and `typescript jsx` as options on the code fence with no success.

Typescript version: `4.4.3`
Node version: `14.17.6`

---

Any tips on what I can try to have this properly type check the markdown file?

Also, is there a glob method to consume all markdown files in a series of directories?

**Comment by paulbrimicombe** [comment]
Hi @kyleknighted, thanks for getting in touch. Unfortunately `tsx` snippets are not currently supported, just plain `TypeScript` snippets. Adding support for `tsx` would be pretty complicated and require additional dependencies on React (which then opens up potential versioning issues) so it's not something I have planned for the near future.

**Comment by kyleknighted** [comment]
Thanks for getting back to me.

**Comment by paulbrimicombe** [comment]
Hi @kyleknighted , it's been a while but I finally got around to adding `tsx` support to this tool. Something like this should work now:

```tsx
import React from 'react';
import { Alert } from 'your-library';

<Alert>
  <i className="fa fa-exclamation-triangle fa-fw fa-lg" />
  <strong>Default</strong> Lorem ipsum dolor sit amet consectetur adipisicing elit.
</Alert>
```
